# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = obj/Debug
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/DEBUG-arbarlith2
  DEFINES   += -DDEBUG
  INCLUDES  += -I.
  CPPFLAGS  += -MMD $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -ggdb
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -rdynamic
  LIBS      += -lGL -lGLU -lGLEW -lSDL -lSDL_mixer -lIL -lILU -lILUT
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(LDFLAGS) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/Release
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/arbarlith2
  DEFINES   += -DNDEBUG
  INCLUDES  += -I.
  CPPFLAGS  += -MMD $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O3
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s
  LIBS      += -lGL -lGLU -lGLEW -lSDL -lSDL_mixer -lIL -lILU -lILUT
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(LDFLAGS) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/Boss.o \
	$(OBJDIR)/SpellIncinerate.o \
	$(OBJDIR)/SpellCasterFSM.o \
	$(OBJDIR)/SpellHeal.o \
	$(OBJDIR)/DetectorProximityMonster.o \
	$(OBJDIR)/Powerup.o \
	$(OBJDIR)/linux.o \
	$(OBJDIR)/Bullet.o \
	$(OBJDIR)/PowerupHeal.o \
	$(OBJDIR)/Monster.o \
	$(OBJDIR)/MyPlayer.o \
	$(OBJDIR)/Spawn.o \
	$(OBJDIR)/Spell.o \
	$(OBJDIR)/win32.o \
	$(OBJDIR)/Explosion.o \
	$(OBJDIR)/SpellFireBall.o \
	$(OBJDIR)/Teleporter.o \
	$(OBJDIR)/PowerupSpell.o \
	$(OBJDIR)/TileGate.o \
	$(OBJDIR)/GateOpener.o \
	$(OBJDIR)/Tile.o \
	$(OBJDIR)/MenuWorldLeadOut.o \
	$(OBJDIR)/lamp.o \
	$(OBJDIR)/StateMachine.o \
	$(OBJDIR)/Effect_TextureReplace_FFP.o \
	$(OBJDIR)/ListPaneWidget.o \
	$(OBJDIR)/fog.o \
	$(OBJDIR)/Key.o \
	$(OBJDIR)/TextureHandle.o \
	$(OBJDIR)/WaitScreen.o \
	$(OBJDIR)/world.o \
	$(OBJDIR)/particle.o \
	$(OBJDIR)/SoundSystem.o \
	$(OBJDIR)/searchfile.o \
	$(OBJDIR)/COLOR.o \
	$(OBJDIR)/3dsLoader.o \
	$(OBJDIR)/Light.o \
	$(OBJDIR)/logstring.o \
	$(OBJDIR)/GameStateSpellMenu.o \
	$(OBJDIR)/ToggleWidget.o \
	$(OBJDIR)/3dmath.o \
	$(OBJDIR)/Effect_Project_Shadows.o \
	$(OBJDIR)/MessageRouter.o \
	$(OBJDIR)/Effect_Z_Only.o \
	$(OBJDIR)/Detector.o \
	$(OBJDIR)/text.o \
	$(OBJDIR)/image.o \
	$(OBJDIR)/ActorFactory.o \
	$(OBJDIR)/CycleTextureSelectorState.o \
	$(OBJDIR)/material.o \
	$(OBJDIR)/MenuOptions.o \
	$(OBJDIR)/EditorKeyDetector.o \
	$(OBJDIR)/timer.o \
	$(OBJDIR)/player.o \
	$(OBJDIR)/ScreenShotTask.o \
	$(OBJDIR)/camera.o \
	$(OBJDIR)/ItemWidget.o \
	$(OBJDIR)/myassert.o \
	$(OBJDIR)/MonsterFSM.o \
	$(OBJDIR)/VisualPriority.o \
	$(OBJDIR)/Map.o \
	$(OBJDIR)/widgetmanager.o \
	$(OBJDIR)/BackdropTexture.o \
	$(OBJDIR)/windowwidget.o \
	$(OBJDIR)/ToggleWidgetText.o \
	$(OBJDIR)/SDLwindow.o \
	$(OBJDIR)/SplashScreen.o \
	$(OBJDIR)/Trigger.o \
	$(OBJDIR)/BoundingBox.o \
	$(OBJDIR)/MenuWorldSelection.o \
	$(OBJDIR)/creature.o \
	$(OBJDIR)/animation.o \
	$(OBJDIR)/Controller.o \
	$(OBJDIR)/Menu.o \
	$(OBJDIR)/EditWidget.o \
	$(OBJDIR)/keyframe.o \
	$(OBJDIR)/GameStateCredits.o \
	$(OBJDIR)/frustum.o \
	$(OBJDIR)/widget.o \
	$(OBJDIR)/TextureManager.o \
	$(OBJDIR)/DebugLabel.o \
	$(OBJDIR)/labelwidget.o \
	$(OBJDIR)/mesh.o \
	$(OBJDIR)/SelectionList.o \
	$(OBJDIR)/Effect_GUI_FFP.o \
	$(OBJDIR)/FPSDisplayToggleKeyDetector.o \
	$(OBJDIR)/Effect_Gouraud_FFP.o \
	$(OBJDIR)/ListenerPrompt.o \
	$(OBJDIR)/Dimmer.o \
	$(OBJDIR)/tstring.o \
	$(OBJDIR)/MusicEngine.o \
	$(OBJDIR)/opengl.o \
	$(OBJDIR)/application.o \
	$(OBJDIR)/file.o \
	$(OBJDIR)/stdafx.o \
	$(OBJDIR)/Effect_Particle_FFP.o \
	$(OBJDIR)/DetectorProximityPlayer.o \
	$(OBJDIR)/ToolBarForEditorTools.o \
	$(OBJDIR)/StateMachineFactory.o \
	$(OBJDIR)/TriggerParticles.o \
	$(OBJDIR)/profile.o \
	$(OBJDIR)/AnimationController.o \
	$(OBJDIR)/PerformanceLabel.o \
	$(OBJDIR)/MenuGameOver.o \
	$(OBJDIR)/DebugDisplayToggleKeyDetector.o \
	$(OBJDIR)/Blur.o \
	$(OBJDIR)/Shadow.o \
	$(OBJDIR)/FileSelectionList.o \
	$(OBJDIR)/horizbar.o \
	$(OBJDIR)/QuadTreeNode.o \
	$(OBJDIR)/LightManager.o \
	$(OBJDIR)/TriggerPrompt.o \
	$(OBJDIR)/ShadowManager.o \
	$(OBJDIR)/item.o \
	$(OBJDIR)/GameStateRun.o \
	$(OBJDIR)/DetectorProximity.o \
	$(OBJDIR)/ListElementWidget.o \
	$(OBJDIR)/SpellMenuKeyDetector.o \
	$(OBJDIR)/PropertyBag.o \
	$(OBJDIR)/object.o \
	$(OBJDIR)/EditorToolBar.o \
	$(OBJDIR)/Effect.o \
	$(OBJDIR)/Switch.o \
	$(OBJDIR)/BlurEffect.o \
	$(OBJDIR)/EffectManager.o \
	$(OBJDIR)/GameStateEditor.o \
	$(OBJDIR)/Listener.o \
	$(OBJDIR)/Md3Loader.o \
	$(OBJDIR)/MenuKeyDetector.o \
	$(OBJDIR)/Effect_Red_FFP.o \
	$(OBJDIR)/mat4.o \
	$(OBJDIR)/ModelLoader.o \
	$(OBJDIR)/Effect_Receive_Shadows.o \
	$(OBJDIR)/ActorSet.o \
	$(OBJDIR)/GameStateMenu.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking arbarlith2
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning arbarlith2
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
endif

$(OBJDIR)/Boss.o: src/Boss.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/SpellIncinerate.o: src/SpellIncinerate.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/SpellCasterFSM.o: src/SpellCasterFSM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/SpellHeal.o: src/SpellHeal.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/DetectorProximityMonster.o: src/DetectorProximityMonster.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Powerup.o: src/Powerup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/linux.o: src/linux.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Bullet.o: src/Bullet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/PowerupHeal.o: src/PowerupHeal.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Monster.o: src/Monster.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MyPlayer.o: src/MyPlayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Spawn.o: src/Spawn.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Spell.o: src/Spell.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/win32.o: src/win32.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Explosion.o: src/Explosion.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/SpellFireBall.o: src/SpellFireBall.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Teleporter.o: src/Teleporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/PowerupSpell.o: src/PowerupSpell.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/TileGate.o: src/TileGate.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/GateOpener.o: src/GateOpener.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Tile.o: src/engine/Tile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MenuWorldLeadOut.o: src/engine/MenuWorldLeadOut.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/lamp.o: src/engine/lamp.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/StateMachine.o: src/engine/StateMachine.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Effect_TextureReplace_FFP.o: src/engine/Effect_TextureReplace_FFP.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ListPaneWidget.o: src/engine/ListPaneWidget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/fog.o: src/engine/fog.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Key.o: src/engine/Key.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/TextureHandle.o: src/engine/TextureHandle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/WaitScreen.o: src/engine/WaitScreen.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/world.o: src/engine/world.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/particle.o: src/engine/particle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/SoundSystem.o: src/engine/SoundSystem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/searchfile.o: src/engine/searchfile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/COLOR.o: src/engine/COLOR.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/3dsLoader.o: src/engine/3dsLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Light.o: src/engine/Light.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/logstring.o: src/engine/logstring.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/GameStateSpellMenu.o: src/engine/GameStateSpellMenu.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ToggleWidget.o: src/engine/ToggleWidget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/3dmath.o: src/engine/3dmath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Effect_Project_Shadows.o: src/engine/Effect_Project_Shadows.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MessageRouter.o: src/engine/MessageRouter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Effect_Z_Only.o: src/engine/Effect_Z_Only.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Detector.o: src/engine/Detector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/text.o: src/engine/text.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/image.o: src/engine/image.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ActorFactory.o: src/engine/ActorFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/CycleTextureSelectorState.o: src/engine/CycleTextureSelectorState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/material.o: src/engine/material.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MenuOptions.o: src/engine/MenuOptions.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/EditorKeyDetector.o: src/engine/EditorKeyDetector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/timer.o: src/engine/timer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/player.o: src/engine/player.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ScreenShotTask.o: src/engine/ScreenShotTask.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/camera.o: src/engine/camera.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ItemWidget.o: src/engine/ItemWidget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/myassert.o: src/engine/myassert.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MonsterFSM.o: src/engine/MonsterFSM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/VisualPriority.o: src/engine/VisualPriority.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Map.o: src/engine/Map.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/widgetmanager.o: src/engine/widgetmanager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/BackdropTexture.o: src/engine/BackdropTexture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/windowwidget.o: src/engine/windowwidget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ToggleWidgetText.o: src/engine/ToggleWidgetText.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/SDLwindow.o: src/engine/SDLwindow.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/SplashScreen.o: src/engine/SplashScreen.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Trigger.o: src/engine/Trigger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/BoundingBox.o: src/engine/BoundingBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MenuWorldSelection.o: src/engine/MenuWorldSelection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/creature.o: src/engine/creature.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/animation.o: src/engine/animation.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Controller.o: src/engine/Controller.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Menu.o: src/engine/Menu.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/EditWidget.o: src/engine/EditWidget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/keyframe.o: src/engine/keyframe.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/GameStateCredits.o: src/engine/GameStateCredits.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/frustum.o: src/engine/frustum.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/widget.o: src/engine/widget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/TextureManager.o: src/engine/TextureManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/DebugLabel.o: src/engine/DebugLabel.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/labelwidget.o: src/engine/labelwidget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/mesh.o: src/engine/mesh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/SelectionList.o: src/engine/SelectionList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Effect_GUI_FFP.o: src/engine/Effect_GUI_FFP.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/FPSDisplayToggleKeyDetector.o: src/engine/FPSDisplayToggleKeyDetector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Effect_Gouraud_FFP.o: src/engine/Effect_Gouraud_FFP.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ListenerPrompt.o: src/engine/ListenerPrompt.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Dimmer.o: src/engine/Dimmer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/tstring.o: src/engine/tstring.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MusicEngine.o: src/engine/MusicEngine.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/opengl.o: src/engine/opengl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/application.o: src/engine/application.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/file.o: src/engine/file.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/stdafx.o: src/engine/stdafx.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Effect_Particle_FFP.o: src/engine/Effect_Particle_FFP.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/DetectorProximityPlayer.o: src/engine/DetectorProximityPlayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ToolBarForEditorTools.o: src/engine/ToolBarForEditorTools.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/StateMachineFactory.o: src/engine/StateMachineFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/TriggerParticles.o: src/engine/TriggerParticles.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/profile.o: src/engine/profile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/AnimationController.o: src/engine/AnimationController.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/PerformanceLabel.o: src/engine/PerformanceLabel.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MenuGameOver.o: src/engine/MenuGameOver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/DebugDisplayToggleKeyDetector.o: src/engine/DebugDisplayToggleKeyDetector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Blur.o: src/engine/Blur.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Shadow.o: src/engine/Shadow.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/FileSelectionList.o: src/engine/FileSelectionList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/horizbar.o: src/engine/horizbar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/QuadTreeNode.o: src/engine/QuadTreeNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/LightManager.o: src/engine/LightManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/TriggerPrompt.o: src/engine/TriggerPrompt.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ShadowManager.o: src/engine/ShadowManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/item.o: src/engine/item.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/GameStateRun.o: src/engine/GameStateRun.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/DetectorProximity.o: src/engine/DetectorProximity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ListElementWidget.o: src/engine/ListElementWidget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/SpellMenuKeyDetector.o: src/engine/SpellMenuKeyDetector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/PropertyBag.o: src/engine/PropertyBag.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/object.o: src/engine/object.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/EditorToolBar.o: src/engine/EditorToolBar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Effect.o: src/engine/Effect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Switch.o: src/engine/Switch.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/BlurEffect.o: src/engine/BlurEffect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/EffectManager.o: src/engine/EffectManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/GameStateEditor.o: src/engine/GameStateEditor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Listener.o: src/engine/Listener.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Md3Loader.o: src/engine/Md3Loader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/MenuKeyDetector.o: src/engine/MenuKeyDetector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Effect_Red_FFP.o: src/engine/Effect_Red_FFP.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/mat4.o: src/engine/mat4.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ModelLoader.o: src/engine/ModelLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/Effect_Receive_Shadows.o: src/engine/Effect_Receive_Shadows.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/ActorSet.o: src/engine/ActorSet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<
$(OBJDIR)/GameStateMenu.o: src/engine/GameStateMenu.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o $@ -c $<

-include $(OBJECTS:%.o=%.d)
