#!/bin/sh
# Launches the game under the debugger
#
# The game expects certain environment variables to be set so that it can
# locate resources &c. This script ensures those are set and launches the
# game.
#
# Also, we cannot rely on being located in the same place where the game was
# originally built. Set environment variables to allow the dynamic linker to
# complete successfully. This is different on the Mac than on Linux.

BASE="`pwd`/redist"
CMD="./redist/bin/arbarlith2"

export ARBARLITH2_SHARE="$BASE/share/arbarlith2"

if [ `uname` == "Darwin" ] ; then
	# We're running on the Mac
	export DYLD_FALLBACK_LIBRARY_PATH="$BASE/lib/:$DYLD_FALLBACK_LIBRARY_PATH"
else
	# Assume a UNIX-like that uses LD_LIBRARY_PATH
	export LD_LIBRARY_PATH="$BASE/lib/:$LD_LIBRARY_PATH"
fi

# Now launch the game, passing our args to the game.
exec gdb $CMD $@
